# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  - group: tf-aws-agent

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    sed "s/{{pat_token}}/${DEVOPS_PAT}/g; s/{{pool_name}}/${POOL_NAME}/g; s/{{agent_name}}/${AWS_AGENT_NAME}/g;" ./utils/terraform_init/aws/cfn/cft-parameters.json > ./cft-parameters.json
    cat ./cft-parameters.json
  displayName: 'Add pat token'
- task: CloudFormationCreateOrUpdateStack@1
  inputs:
    awsCredentials: 'AWS_Conn'
    regionName: 'eu-north-1'
    stackName: 'az-tf-agent'
    templateSource: 'file'
    templateFile: './utils/terraform_init/aws/cfn/azdevops-agent-vm-cft.yaml'
    templateParametersFile: './cft-parameters.json'