USE [master]
GO

/****** Object:  Database [OAPDatabase]    Script Date: 13/11/2018 00:23:33 ******/
CREATE DATABASE [OAPDatabase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'OAPDatabase', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\OAPDatabase.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'OAPDatabase_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\OAPDatabase_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [OAPDatabase] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [OAPDatabase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [OAPDatabase] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [OAPDatabase] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [OAPDatabase] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [OAPDatabase] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [OAPDatabase] SET ARITHABORT OFF 
GO

ALTER DATABASE [OAPDatabase] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [OAPDatabase] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [OAPDatabase] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [OAPDatabase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [OAPDatabase] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [OAPDatabase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [OAPDatabase] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [OAPDatabase] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [OAPDatabase] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [OAPDatabase] SET  DISABLE_BROKER 
GO

ALTER DATABASE [OAPDatabase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [OAPDatabase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [OAPDatabase] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [OAPDatabase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [OAPDatabase] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [OAPDatabase] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [OAPDatabase] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [OAPDatabase] SET RECOVERY FULL 
GO

ALTER DATABASE [OAPDatabase] SET  MULTI_USER 
GO

ALTER DATABASE [OAPDatabase] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [OAPDatabase] SET DB_CHAINING OFF 
GO

ALTER DATABASE [OAPDatabase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [OAPDatabase] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [OAPDatabase] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [OAPDatabase] SET QUERY_STORE = OFF
GO

USE [OAPDatabase]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [OAPDatabase] SET  READ_WRITE 
GO


-------------

USE [OAPDatabase]
GO

/****** Object:  Table [dbo].[SearchLog]    Script Date: 11/11/2018 15:39:56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SearchLog](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[SearchKey] [varchar](255) NOT NULL,
	[Result] [varchar](255) NOT NULL,
	[CreatedDate] [datetime] NOT NULL,
	[UpdatedDate] [datetime] NULL,
	[Active] [bit] NOT NULL,
 CONSTRAINT [PK_SearchLog] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SearchLog] ADD  CONSTRAINT [DF_SearchLog_Active]  DEFAULT ((1)) FOR [Active]
GO

------------------------------------------------------------------------------

/****** Object:  Table [dbo].[DishType]    Script Date: 11/11/2018 15:39:56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DishType](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](255) NOT NULL,
	[Order] [int] NOT NULL,
	[CreatedDate] [datetime] NOT NULL,
	[UpdatedDate] [datetime] NULL,
	[Active] [bit] NOT NULL,
 CONSTRAINT [PK_DishType] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[DishType] ADD  CONSTRAINT [DF_DishType_Active]  DEFAULT ((1)) FOR [Active]
GO
----------------------------------------------------------------------------

/****** Object:  Table [dbo].[Period]    Script Date: 11/11/2018 15:39:56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Period](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](255) NOT NULL,
	[CreatedDate] [datetime] NOT NULL,
	[UpdatedDate] [datetime] NULL,
	[Active] [bit] NOT NULL,
 CONSTRAINT [PK_Period] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Period] ADD  CONSTRAINT [DF_Period_Active]  DEFAULT ((1)) FOR [Active]
GO

----------------------------------------------------------------------------

/****** Object:  Table [dbo].[Dish]    Script Date: 11/11/2018 15:39:56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Dish](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Description] [varchar](255) NOT NULL,
	[PeriodId] [int] NOT NULL,
	[DishTypeId] [int] NOT NULL,
	[CreatedDate] [datetime] NOT NULL,
	[UpdatedDate] [datetime] NULL,
	[Active] [bit] NOT NULL,
 CONSTRAINT [PK_Dish] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Dish] ADD  CONSTRAINT [DF_Dish_Active]  DEFAULT ((1)) FOR [Active]
GO

---------------------------------------

/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Period SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.DishType SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Dish ADD CONSTRAINT
	FK_Dish_DishType FOREIGN KEY
	(
	DishTypeId
	) REFERENCES dbo.DishType
	(
	Id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.Dish ADD CONSTRAINT
	FK_Dish_Period FOREIGN KEY
	(
	PeriodId
	) REFERENCES dbo.Period
	(
	Id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.Dish SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
